/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab7p2_edgarmembreno;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author edgarmembreno
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_CrearAstro = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        idAstro = new javax.swing.JTextField();
        nombreAstro = new javax.swing.JTextField();
        apellidoAstro = new javax.swing.JTextField();
        nacionalidadAstro = new javax.swing.JTextField();
        contexturaAstro = new javax.swing.JTextField();
        tituloAstro = new javax.swing.JTextField();
        pesoAstro = new javax.swing.JTextField();
        misionesAstro = new javax.swing.JTextField();
        agregarAstro = new javax.swing.JButton();
        jd_CrearNave = new javax.swing.JDialog();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        nombreNave = new javax.swing.JTextField();
        idNave = new javax.swing.JTextField();
        personasNave = new javax.swing.JTextField();
        despegueNave = new javax.swing.JTextField();
        atterizajeNave = new javax.swing.JTextField();
        velocidadNave = new javax.swing.JTextField();
        distanciaNave = new javax.swing.JTextField();
        combustibleNave = new javax.swing.JTextField();
        reservaNave = new javax.swing.JTextField();
        AgregarNave = new javax.swing.JButton();
        jd_Creardestino = new javax.swing.JDialog();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        nombreDestino = new javax.swing.JTextField();
        distanciaDestino = new javax.swing.JTextField();
        supeficieDestino = new javax.swing.JTextField();
        sauracionDestino = new javax.swing.JTextField();
        agregarDestino = new javax.swing.JButton();
        jd_ListaNaves = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_naves = new javax.swing.JList<>();
        popup_Naves = new javax.swing.JPopupMenu();
        modficiar = new javax.swing.JMenuItem();
        eliminar = new javax.swing.JMenuItem();
        usarNave = new javax.swing.JMenuItem();
        jd_ListaAstro = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_Astro = new javax.swing.JList<>();
        popup_Personas = new javax.swing.JPopupMenu();
        Eliminar = new javax.swing.JMenuItem();
        Modificar = new javax.swing.JMenuItem();
        AgregarTripulante = new javax.swing.JMenuItem();
        AgregarDestino = new javax.swing.JMenuItem();
        jd_ListaDestinos = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_Destino = new javax.swing.JList<>();
        popup_Destinos = new javax.swing.JPopupMenu();
        Eliminar1 = new javax.swing.JMenuItem();
        Modificar1 = new javax.swing.JMenuItem();
        AgregarDestinoVuelo = new javax.swing.JMenuItem();
        EmpezarViaje = new javax.swing.JMenuItem();
        jd_Viaje = new javax.swing.JDialog();
        jLabel26 = new javax.swing.JLabel();
        progress_Distancia = new javax.swing.JProgressBar();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        progress_Distancia1 = new javax.swing.JProgressBar();
        jd_ModiciarNave = new javax.swing.JDialog();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        nombreNave1 = new javax.swing.JTextField();
        idNave1 = new javax.swing.JTextField();
        personasNave1 = new javax.swing.JTextField();
        despegueNave1 = new javax.swing.JTextField();
        atterizajeNave1 = new javax.swing.JTextField();
        velocidadNave1 = new javax.swing.JTextField();
        distanciaNave1 = new javax.swing.JTextField();
        combustibleNave1 = new javax.swing.JTextField();
        reservaNave1 = new javax.swing.JTextField();
        md_Nave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CrearAstro = new javax.swing.JButton();
        CrearNave = new javax.swing.JButton();
        CrearDestino = new javax.swing.JButton();
        empezarSimulacion = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        jLabel2.setText("Astronautas");

        jLabel3.setText("id");

        jLabel4.setText("Nombre");

        jLabel5.setText("Apellido");

        jLabel6.setText("Nacionalidad");

        jLabel7.setText("Titulo");

        jLabel8.setText("Contextura");

        jLabel9.setText("Peso");

        jLabel10.setText("Misiones");

        contexturaAstro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contexturaAstroActionPerformed(evt);
            }
        });

        agregarAstro.setText("Agregar");
        agregarAstro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAstroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_CrearAstroLayout = new javax.swing.GroupLayout(jd_CrearAstro.getContentPane());
        jd_CrearAstro.getContentPane().setLayout(jd_CrearAstroLayout);
        jd_CrearAstroLayout.setHorizontalGroup(
            jd_CrearAstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearAstroLayout.createSequentialGroup()
                .addGroup(jd_CrearAstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jd_CrearAstroLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jLabel2))
                    .addGroup(jd_CrearAstroLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jd_CrearAstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addGroup(jd_CrearAstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CrearAstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(idAstro)
                                .addComponent(apellidoAstro)
                                .addComponent(nacionalidadAstro)
                                .addComponent(tituloAstro)
                                .addComponent(contexturaAstro)
                                .addComponent(pesoAstro)
                                .addComponent(misionesAstro, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                            .addComponent(nombreAstro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarAstro, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(25, 25, 25)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jd_CrearAstroLayout.setVerticalGroup(
            jd_CrearAstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearAstroLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jd_CrearAstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idAstro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearAstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nombreAstro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jd_CrearAstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(apellidoAstro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearAstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nacionalidadAstro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jd_CrearAstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tituloAstro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jd_CrearAstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(contexturaAstro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearAstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(pesoAstro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearAstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(misionesAstro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(agregarAstro)
                .addGap(17, 17, 17))
        );

        jLabel11.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        jLabel11.setText("NAVE");

        jLabel12.setText("Nombre");

        jLabel13.setText("Identificador");

        jLabel14.setText("PersonasMax");

        jLabel15.setText("Tiempo de Despegue");

        jLabel16.setText("Tiempo de Aterrizaje");

        jLabel17.setText("Velocidad");

        jLabel18.setText("Distancia maxima");

        jLabel19.setText("Combustible");

        jLabel20.setText("Reserva");

        AgregarNave.setText("Agregar");
        AgregarNave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarNaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_CrearNaveLayout = new javax.swing.GroupLayout(jd_CrearNave.getContentPane());
        jd_CrearNave.getContentPane().setLayout(jd_CrearNaveLayout);
        jd_CrearNaveLayout.setHorizontalGroup(
            jd_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CrearNaveLayout.createSequentialGroup()
                .addGroup(jd_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_CrearNaveLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AgregarNave))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_CrearNaveLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_CrearNaveLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jd_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_CrearNaveLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idNave, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_CrearNaveLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nombreNave, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_CrearNaveLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(reservaNave, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_CrearNaveLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(personasNave, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_CrearNaveLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(despegueNave, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_CrearNaveLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(atterizajeNave, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_CrearNaveLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(velocidadNave, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_CrearNaveLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(distanciaNave, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_CrearNaveLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(combustibleNave, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(152, 152, 152))
        );
        jd_CrearNaveLayout.setVerticalGroup(
            jd_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearNaveLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jd_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(nombreNave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(idNave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(personasNave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(despegueNave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(atterizajeNave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(velocidadNave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(distanciaNave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(combustibleNave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CrearNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(reservaNave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(AgregarNave)
                .addGap(32, 32, 32))
        );

        jLabel21.setText("Nombre");

        jLabel22.setText("Distancia");

        jLabel23.setText("Superficie");

        jLabel24.setText("Saturacion");

        jLabel25.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel25.setText("Destino");

        agregarDestino.setText("Agregar");
        agregarDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarDestinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_CreardestinoLayout = new javax.swing.GroupLayout(jd_Creardestino.getContentPane());
        jd_Creardestino.getContentPane().setLayout(jd_CreardestinoLayout);
        jd_CreardestinoLayout.setHorizontalGroup(
            jd_CreardestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CreardestinoLayout.createSequentialGroup()
                .addGap(231, 231, 231)
                .addComponent(jLabel25)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CreardestinoLayout.createSequentialGroup()
                .addGroup(jd_CreardestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_CreardestinoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(agregarDestino))
                    .addGroup(jd_CreardestinoLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(jd_CreardestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addGroup(jd_CreardestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sauracionDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(supeficieDestino)
                            .addComponent(distanciaDestino)
                            .addComponent(nombreDestino))))
                .addGap(159, 159, 159))
        );
        jd_CreardestinoLayout.setVerticalGroup(
            jd_CreardestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CreardestinoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel25)
                .addGap(51, 51, 51)
                .addGroup(jd_CreardestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(nombreDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CreardestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(distanciaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CreardestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(supeficieDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_CreardestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(sauracionDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(agregarDestino)
                .addGap(18, 18, 18))
        );

        jl_naves.setModel(new DefaultListModel());
        jl_naves.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_navesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jl_naves);

        javax.swing.GroupLayout jd_ListaNavesLayout = new javax.swing.GroupLayout(jd_ListaNaves.getContentPane());
        jd_ListaNaves.getContentPane().setLayout(jd_ListaNavesLayout);
        jd_ListaNavesLayout.setHorizontalGroup(
            jd_ListaNavesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ListaNavesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_ListaNavesLayout.setVerticalGroup(
            jd_ListaNavesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ListaNavesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        modficiar.setText("Modificar");
        modficiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modficiarActionPerformed(evt);
            }
        });
        popup_Naves.add(modficiar);

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });
        popup_Naves.add(eliminar);

        usarNave.setText("UsarNave");
        usarNave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usarNaveActionPerformed(evt);
            }
        });
        popup_Naves.add(usarNave);

        jl_Astro.setModel(new DefaultListModel());
        jl_Astro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_AstroMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jl_Astro);

        javax.swing.GroupLayout jd_ListaAstroLayout = new javax.swing.GroupLayout(jd_ListaAstro.getContentPane());
        jd_ListaAstro.getContentPane().setLayout(jd_ListaAstroLayout);
        jd_ListaAstroLayout.setHorizontalGroup(
            jd_ListaAstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ListaAstroLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jd_ListaAstroLayout.setVerticalGroup(
            jd_ListaAstroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ListaAstroLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        Eliminar.setText("ELIMINAR");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        popup_Personas.add(Eliminar);

        Modificar.setText("MODIFICAR");
        popup_Personas.add(Modificar);

        AgregarTripulante.setText("AgregarTripulante");
        AgregarTripulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarTripulanteActionPerformed(evt);
            }
        });
        popup_Personas.add(AgregarTripulante);

        AgregarDestino.setText("Destino");
        AgregarDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarDestinoActionPerformed(evt);
            }
        });
        popup_Personas.add(AgregarDestino);

        jl_Destino.setModel(new DefaultListModel());
        jl_Destino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_DestinoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jl_Destino);

        javax.swing.GroupLayout jd_ListaDestinosLayout = new javax.swing.GroupLayout(jd_ListaDestinos.getContentPane());
        jd_ListaDestinos.getContentPane().setLayout(jd_ListaDestinosLayout);
        jd_ListaDestinosLayout.setHorizontalGroup(
            jd_ListaDestinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ListaDestinosLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jd_ListaDestinosLayout.setVerticalGroup(
            jd_ListaDestinosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ListaDestinosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        Eliminar1.setText("ELIMINAR");
        Eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar1ActionPerformed(evt);
            }
        });
        popup_Destinos.add(Eliminar1);

        Modificar1.setText("MODIFICAR");
        popup_Destinos.add(Modificar1);

        AgregarDestinoVuelo.setText("AgregarDestino");
        AgregarDestinoVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarDestinoVueloActionPerformed(evt);
            }
        });
        popup_Destinos.add(AgregarDestinoVuelo);

        EmpezarViaje.setText("EmpezarViaje");
        EmpezarViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpezarViajeActionPerformed(evt);
            }
        });
        popup_Destinos.add(EmpezarViaje);

        jLabel26.setText("Distancia Recorrida");

        progress_Distancia.setMaximum(1000);
        progress_Distancia.setToolTipText("");
        progress_Distancia.setString(Integer.toString(progress_Distancia.getValue())+" Kilometros");
        progress_Distancia.setStringPainted(true);

        jLabel27.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel27.setText("Viaje");

        jLabel28.setText("Distancia Tanque 2");

        progress_Distancia1.setMaximum(1000);
        progress_Distancia1.setToolTipText("");
        progress_Distancia1.setString(Integer.toString(progress_Distancia.getValue())+" Kilometros");
        progress_Distancia1.setStringPainted(true);

        javax.swing.GroupLayout jd_ViajeLayout = new javax.swing.GroupLayout(jd_Viaje.getContentPane());
        jd_Viaje.getContentPane().setLayout(jd_ViajeLayout);
        jd_ViajeLayout.setHorizontalGroup(
            jd_ViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ViajeLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(jd_ViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ViajeLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(288, 288, 288))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ViajeLayout.createSequentialGroup()
                        .addGroup(jd_ViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jd_ViajeLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(18, 18, 18)
                                .addComponent(progress_Distancia1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_ViajeLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(18, 18, 18)
                                .addComponent(progress_Distancia, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(54, 54, 54))))
        );
        jd_ViajeLayout.setVerticalGroup(
            jd_ViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ViajeLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel27)
                .addGap(88, 88, 88)
                .addGroup(jd_ViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(progress_Distancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addGroup(jd_ViajeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(progress_Distancia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(151, Short.MAX_VALUE))
        );

        jLabel29.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        jLabel29.setText("NAVE");

        jLabel30.setText("Nombre");

        jLabel31.setText("Identificador");

        jLabel32.setText("PersonasMax");

        jLabel33.setText("Tiempo de Despegue");

        jLabel34.setText("Tiempo de Aterrizaje");

        jLabel35.setText("Velocidad");

        jLabel36.setText("Distancia maxima");

        jLabel37.setText("Combustible");

        jLabel38.setText("Reserva");

        md_Nave.setText("Modificar");
        md_Nave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                md_NaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_ModiciarNaveLayout = new javax.swing.GroupLayout(jd_ModiciarNave.getContentPane());
        jd_ModiciarNave.getContentPane().setLayout(jd_ModiciarNaveLayout);
        jd_ModiciarNaveLayout.setHorizontalGroup(
            jd_ModiciarNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ModiciarNaveLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel29)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_ModiciarNaveLayout.createSequentialGroup()
                .addGroup(jd_ModiciarNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_ModiciarNaveLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(md_Nave))
                    .addGroup(jd_ModiciarNaveLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jd_ModiciarNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_ModiciarNaveLayout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idNave1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_ModiciarNaveLayout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nombreNave1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_ModiciarNaveLayout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(reservaNave1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_ModiciarNaveLayout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(personasNave1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_ModiciarNaveLayout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                                .addComponent(despegueNave1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_ModiciarNaveLayout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(atterizajeNave1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_ModiciarNaveLayout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(velocidadNave1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_ModiciarNaveLayout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(distanciaNave1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_ModiciarNaveLayout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(combustibleNave1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(102, 102, 102))
        );
        jd_ModiciarNaveLayout.setVerticalGroup(
            jd_ModiciarNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ModiciarNaveLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addGroup(jd_ModiciarNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(nombreNave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_ModiciarNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(idNave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_ModiciarNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(personasNave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_ModiciarNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(despegueNave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_ModiciarNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(atterizajeNave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_ModiciarNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35)
                    .addComponent(velocidadNave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_ModiciarNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(distanciaNave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_ModiciarNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(combustibleNave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_ModiciarNaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38)
                    .addComponent(reservaNave1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(md_Nave)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
        jLabel1.setText("NASA");

        CrearAstro.setText("Crear Astronautas");
        CrearAstro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearAstroActionPerformed(evt);
            }
        });

        CrearNave.setText("Crear Nave");
        CrearNave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearNaveActionPerformed(evt);
            }
        });

        CrearDestino.setText("Crear Destino");
        CrearDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearDestinoActionPerformed(evt);
            }
        });

        empezarSimulacion.setText("Empezar Simulacion");
        empezarSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empezarSimulacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(jLabel1)
                .addContainerGap(299, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CrearNave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CrearAstro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CrearDestino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(empezarSimulacion)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addComponent(CrearAstro)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(CrearNave)
                        .addGap(38, 38, 38)
                        .addComponent(CrearDestino))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(empezarSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contexturaAstroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contexturaAstroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contexturaAstroActionPerformed

    private void agregarAstroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAstroActionPerformed
        try {
            int id = Integer.parseInt(idAstro.getText());
            String nombre = nombreAstro.getText();
            String apellido = apellidoAstro.getText();
            String nacionalidad = nacionalidadAstro.getText();
            String titulo = tituloAstro.getText();
            String contextura = contexturaAstro.getText();
            String peso = pesoAstro.getText();
            String misiones = misionesAstro.getText();

            astronautas x = new astronautas(id, nombre, apellido, nacionalidad, titulo, contextura, peso, misiones);
            adminAstro ap = new adminAstro("./Astronautas.cbm");
            ap.cargarArchivo();
            ap.setAstro(x);
            ap.escribirArchivo();

            idAstro.setText("");
            nombreAstro.setText("");
            apellidoAstro.setText("");
            nacionalidadAstro.setText("");
            tituloAstro.setText("");
            contexturaAstro.setText("");
            pesoAstro.setText("");
            misionesAstro.setText("");
            jd_CrearAstro.hide();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "OCURRIO UN ERROR");
        }


    }//GEN-LAST:event_agregarAstroActionPerformed

    private void CrearAstroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearAstroActionPerformed
        jd_CrearAstro.setModal(true);
        jd_CrearAstro.pack();
        jd_CrearAstro.setLocationRelativeTo(this);
        jd_CrearAstro.setVisible(true);

    }//GEN-LAST:event_CrearAstroActionPerformed

    private void AgregarNaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarNaveActionPerformed
        try {
            String nombre = nombreNave.getText();
            String identificador = idNave.getText();
            int personasMax = Integer.parseInt(personasNave.getText());
            int depegue = Integer.parseInt(despegueNave.getText());
            int aterri = Integer.parseInt(atterizajeNave.getText());
            int velocidad = Integer.parseInt(velocidadNave.getText());
            int distanciaMax = Integer.parseInt(distanciaNave.getText());
            int combusti = Integer.parseInt(combustibleNave.getText());
            int reserva = Integer.parseInt(reservaNave.getText());

            naves x = new naves(nombre, identificador, personasMax, depegue, aterri, velocidad, distanciaMax, combusti, reserva);
            adminNaves ap = new adminNaves("./Naves.cbm");
            ap.cargarArchivo();
            ap.setNaves(x);
            ap.escribirArchivo();

            nombreNave.setText("");
            idNave.setText("");
            personasNave.setText("");
            despegueNave.setText("");
            atterizajeNave.setText("");
            velocidadNave.setText("");
            distanciaNave.setText("");
            combustibleNave.setText("");
            reservaNave.setText("");
            jd_CrearNave.hide();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "OCURRIO UN ERROR");
        }


    }//GEN-LAST:event_AgregarNaveActionPerformed

    private void CrearNaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearNaveActionPerformed
        jd_CrearNave.setModal(true);
        jd_CrearNave.pack();
        jd_CrearNave.setLocationRelativeTo(this);
        jd_CrearNave.setVisible(true);
    }//GEN-LAST:event_CrearNaveActionPerformed

    private void agregarDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarDestinoActionPerformed
        try {
            String nombre = nombreDestino.getText();
            int distancia = Integer.parseInt(distanciaDestino.getText());
            String superficie = supeficieDestino.getText();
            int saturacion = Integer.parseInt(sauracionDestino.getText());

            destino x = new destino(nombre, distancia, superficie, saturacion);
            adminDestino ap = new adminDestino("./Destinos.cbm");
            ap.cargarArchivo();
            ap.setDestino(x);
            ap.escribirArchivo();

            nombreDestino.setText("");
            distanciaDestino.setText("");
            supeficieDestino.setText("");
            sauracionDestino.setText("");
            jd_Creardestino.hide();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "OCURRIO UN ERROR");
        }


    }//GEN-LAST:event_agregarDestinoActionPerformed

    private void CrearDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearDestinoActionPerformed
        jd_Creardestino.setModal(true);
        jd_Creardestino.pack();
        jd_Creardestino.setLocationRelativeTo(this);
        jd_Creardestino.setVisible(true);

    }//GEN-LAST:event_CrearDestinoActionPerformed

    private void jl_navesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_navesMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            if (jl_naves.getSelectedIndex() >= 0) {
                poNave = jl_naves.getSelectedIndex();
                popup_Naves.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jl_navesMouseClicked

    private void empezarSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empezarSimulacionActionPerformed
        DefaultListModel modelo = (DefaultListModel) jl_naves.getModel();
        modelo.removeAllElements();
        adminNaves ap = new adminNaves("./Naves.cbm");
        ap.cargarArchivo();
        for (int i = 0; i < ap.getListaNaves().size(); i++) {
            modelo.addElement(ap.getListaNaves().get(i));
        }
        jl_naves.setModel(modelo);
        jd_ListaNaves.setModal(true);
        jd_ListaNaves.pack();
        jd_ListaNaves.setLocationRelativeTo(this);
        jd_ListaNaves.setVisible(true);


    }//GEN-LAST:event_empezarSimulacionActionPerformed

    private void jl_AstroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_AstroMouseClicked
        if (evt.isMetaDown()) {
            if (jl_Astro.getSelectedIndex() >= 0) {
                poNave = jl_Astro.getSelectedIndex();
                popup_Personas.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jl_AstroMouseClicked

    private void usarNaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usarNaveActionPerformed
        DefaultListModel modelo = (DefaultListModel) jl_Astro.getModel();
        modelo.removeAllElements();
        adminAstro ap = new adminAstro("./Astronautas.cbm");
        ap.cargarArchivo();
        for (int i = 0; i < ap.getListaAstro().size(); i++) {
            modelo.addElement(ap.getListaAstro().get(i));
        }
        jl_Astro.setModel(modelo);
        jd_ListaAstro.setModal(true);
        jd_ListaAstro.pack();
        jd_ListaAstro.setLocationRelativeTo(this);
        jd_ListaAstro.setVisible(true);


    }//GEN-LAST:event_usarNaveActionPerformed

    private void AgregarTripulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarTripulanteActionPerformed
        adminAstro ap = new adminAstro("./Astronautas.cbm");
        ap.cargarArchivo();
        for (int i = 0; i < ap.getListaAstro().size(); i++) {
            int id = ap.getListaAstro().get(i).getId();
            String nombre = ap.getListaAstro().get(i).getNombre();
            String apellido = ap.getListaAstro().get(i).getApellido();
            String nacionalidad = ap.getListaAstro().get(i).getNacionalidad();
            String titulo = ap.getListaAstro().get(i).getTitulo();
            String contex = ap.getListaAstro().get(i).getContextura();
            String peso = ap.getListaAstro().get(i).getPeso();
            String misones = ap.getListaAstro().get(i).getMisones();

            astronautas x = new astronautas(id, nombre, apellido, nacionalidad, titulo, contex, peso, misones);

            adminNaves ad = new adminNaves("./Naves.cbm");
            ad.cargarArchivo();
            ad.getListaNaves().get(i).getAstronautas().add(x);
            ap.escribirArchivo();

        }
        JOptionPane.showMessageDialog(this, "Se agrego tripulante");


    }//GEN-LAST:event_AgregarTripulanteActionPerformed

    private void AgregarDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarDestinoActionPerformed
        DefaultListModel modelo = (DefaultListModel) jl_Destino.getModel();
        modelo.removeAllElements();
        adminDestino ap = new adminDestino("./Destinos.cbm");
        ap.cargarArchivo();
        for (int i = 0; i < ap.getListaDestinos().size(); i++) {
            modelo.addElement(ap.getListaDestinos().get(i));
        }
        jl_Destino.setModel(modelo);
        jd_ListaDestinos.setModal(true);
        jd_ListaDestinos.pack();
        jd_ListaDestinos.setLocationRelativeTo(this);
        jd_ListaDestinos.setVisible(true);


    }//GEN-LAST:event_AgregarDestinoActionPerformed

    private void AgregarDestinoVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarDestinoVueloActionPerformed
        adminDestino ap = new adminDestino("./Destinos.cbm");
        ap.cargarArchivo();
        for (int i = 0; i < ap.getListaDestinos().size(); i++) {
            String nombre = ap.getListaDestinos().get(i).getNombre();
            int distancia = ap.getListaDestinos().get(i).getDistancia();
            String superf = ap.getListaDestinos().get(i).getSuperficie();
            int saturacion = ap.getListaDestinos().get(i).getSaturacion();

            destino x = new destino(nombre, distancia, superf, saturacion);
            adminNaves ad = new adminNaves("./Naves.cbm");
            ad.cargarArchivo();
            ad.getListaNaves().get(i).getDestino().add(x);
            ap.escribirArchivo();

        }


    }//GEN-LAST:event_AgregarDestinoVueloActionPerformed

    private void jl_DestinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_DestinoMouseClicked
        if (evt.isMetaDown()) {
            if (jl_Destino.getSelectedIndex() >= 0) {
                poNave = jl_Destino.getSelectedIndex();
                popup_Destinos.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jl_DestinoMouseClicked

    private void EmpezarViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpezarViajeActionPerformed
        try {
            adminNaves ad = new adminNaves("./Naves.cbm");
            ad.cargarArchivo();
            if (ad.getListaNaves().get(poNave).getAstronautas().get(poNave).getTitulo().equalsIgnoreCase("Fisico")
                    && ad.getListaNaves().get(poNave).getAstronautas().get(poNave).getTitulo().equalsIgnoreCase("Astrofisico")
                    && ad.getListaNaves().get(poNave).getAstronautas().get(poNave).getTitulo().equalsIgnoreCase("Ingeniero")&& ad.getListaNaves().get(poNave).getPersonasMax()>=3) {
                via = new Viaje(progress_Distancia);
                via.setPo(jl_Destino.getSelectedIndex());
                naves x = ad.getListaNaves().get(poNave);
                via.setNave(x);
                try {
                    via.start();
                } catch (Exception e) {
                }
                via.setAvanzar(true);
                jd_Viaje.setModal(true);
                jd_Viaje.pack();
                jd_Viaje.setLocationRelativeTo(this);
                jd_Viaje.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(this, "Debe de tener un fisico, astrofisico y un ingeniero para lograr la mision");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "OCURRIO UN ERROR");
        }


    }//GEN-LAST:event_EmpezarViajeActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        try {
            int po = jl_naves.getSelectedIndex();
            DefaultListModel modelo = (DefaultListModel) jl_naves.getModel();
            modelo.remove(po);
            jl_naves.setModel(modelo);
            adminNaves ad = new adminNaves("./Naves.cbm");
            ad.cargarArchivo();
            ad.getListaNaves().remove(po);
            ad.escribirArchivo();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "OCURRIO UN ERROR");
        }
    }//GEN-LAST:event_eliminarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        try {
            int po = jl_Astro.getSelectedIndex();
            DefaultListModel modelo = (DefaultListModel) jl_Astro.getModel();
            modelo.remove(po);
            jl_Astro.setModel(modelo);
            adminAstro ap = new adminAstro("./Astronautas.cbm");
            ap.cargarArchivo();
            ap.getListaAstro().remove(po);
            ap.escribirArchivo();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "OCURRIO UN ERROR");
        }


    }//GEN-LAST:event_EliminarActionPerformed

    private void Eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar1ActionPerformed
        try {
            int po = jl_Destino.getSelectedIndex();
            DefaultListModel modelo = (DefaultListModel) jl_Destino.getModel();
            modelo.remove(po);
            jl_Destino.setModel(modelo);
            adminDestino ap = new adminDestino("./Destinos.cbm");
            ap.cargarArchivo();
            ap.getListaDestinos().remove(po);
            ap.escribirArchivo();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "OCURRIO UN ERROR");
        }
    }//GEN-LAST:event_Eliminar1ActionPerformed

    private void modficiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modficiarActionPerformed
        try {
            int po = jl_naves.getSelectedIndex();
            adminNaves ad = new adminNaves("./Naves.cbm");
            ad.cargarArchivo();
            naves x = ad.getListaNaves().get(po);

            nombreNave1.setText(x.getNombre());
            idNave1.setText(x.getIdentificador());

            jd_ModiciarNave.setModal(true);
            jd_ModiciarNave.pack();
            jd_ModiciarNave.setLocationRelativeTo(this);
            jd_ModiciarNave.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "OCURRIO UN ERROR");
        }

    }//GEN-LAST:event_modficiarActionPerformed

    private void md_NaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_md_NaveActionPerformed

        try {
            int po = jl_naves.getSelectedIndex();
            adminNaves ap = new adminNaves("./Naves.cbm");
            ap.cargarArchivo();
            String nombre = nombreNave1.getText();
            String indentificador = idNave1.getText();
            int personas = Integer.parseInt(personasNave1.getText());
            int despegue = Integer.parseInt(despegueNave1.getText());

            ap.getListaNaves().get(po).setNombre(nombre);
            ap.getListaNaves().get(po).setIdentificador(indentificador);
            ap.getListaNaves().get(po).setPersonasMax(personas);
            ap.getListaNaves().get(po).setDespegue(despegue);

            ap.escribirArchivo();
            DefaultListModel modelo = (DefaultListModel) jl_naves.getModel();
            jl_naves.setModel(modelo);
            jd_ModiciarNave.hide();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "OCURRIO UN ERROR");
        }


    }//GEN-LAST:event_md_NaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgregarDestino;
    private javax.swing.JMenuItem AgregarDestinoVuelo;
    private javax.swing.JButton AgregarNave;
    private javax.swing.JMenuItem AgregarTripulante;
    private javax.swing.JButton CrearAstro;
    private javax.swing.JButton CrearDestino;
    private javax.swing.JButton CrearNave;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JMenuItem Eliminar1;
    private javax.swing.JMenuItem EmpezarViaje;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JMenuItem Modificar1;
    private javax.swing.JButton agregarAstro;
    private javax.swing.JButton agregarDestino;
    private javax.swing.JTextField apellidoAstro;
    private javax.swing.JTextField atterizajeNave;
    private javax.swing.JTextField atterizajeNave1;
    private javax.swing.JTextField combustibleNave;
    private javax.swing.JTextField combustibleNave1;
    private javax.swing.JTextField contexturaAstro;
    private javax.swing.JTextField despegueNave;
    private javax.swing.JTextField despegueNave1;
    private javax.swing.JTextField distanciaDestino;
    private javax.swing.JTextField distanciaNave;
    private javax.swing.JTextField distanciaNave1;
    private javax.swing.JMenuItem eliminar;
    private javax.swing.JButton empezarSimulacion;
    private javax.swing.JTextField idAstro;
    private javax.swing.JTextField idNave;
    private javax.swing.JTextField idNave1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JDialog jd_CrearAstro;
    private javax.swing.JDialog jd_CrearNave;
    private javax.swing.JDialog jd_Creardestino;
    private javax.swing.JDialog jd_ListaAstro;
    private javax.swing.JDialog jd_ListaDestinos;
    private javax.swing.JDialog jd_ListaNaves;
    private javax.swing.JDialog jd_ModiciarNave;
    private javax.swing.JDialog jd_Viaje;
    private javax.swing.JList<String> jl_Astro;
    private javax.swing.JList<String> jl_Destino;
    private javax.swing.JList<String> jl_naves;
    private javax.swing.JButton md_Nave;
    private javax.swing.JTextField misionesAstro;
    private javax.swing.JMenuItem modficiar;
    private javax.swing.JTextField nacionalidadAstro;
    private javax.swing.JTextField nombreAstro;
    private javax.swing.JTextField nombreDestino;
    private javax.swing.JTextField nombreNave;
    private javax.swing.JTextField nombreNave1;
    private javax.swing.JTextField personasNave;
    private javax.swing.JTextField personasNave1;
    private javax.swing.JTextField pesoAstro;
    private javax.swing.JPopupMenu popup_Destinos;
    private javax.swing.JPopupMenu popup_Naves;
    private javax.swing.JPopupMenu popup_Personas;
    public javax.swing.JProgressBar progress_Distancia;
    public javax.swing.JProgressBar progress_Distancia1;
    private javax.swing.JTextField reservaNave;
    private javax.swing.JTextField reservaNave1;
    private javax.swing.JTextField sauracionDestino;
    private javax.swing.JTextField supeficieDestino;
    private javax.swing.JTextField tituloAstro;
    private javax.swing.JMenuItem usarNave;
    private javax.swing.JTextField velocidadNave;
    private javax.swing.JTextField velocidadNave1;
    // End of variables declaration//GEN-END:variables
 int poNave;
    Viaje via;
}
